Repository googleapis/java-webrisk, pull requests merged in 2020-06, with the labels that each got.

#165 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#167 chore: regenerate with updated protoc
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/CompressionType.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/ComputeThreatListDiffRequest.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/ComputeThreatListDiffResponse.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/CreateSubmissionRequest.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/RawHashes.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/RawIndices.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/RiceDeltaEncoding.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/SearchHashesRequest.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/SearchHashesResponse.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/SearchUrisRequest.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/SearchUrisResponse.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/Submission.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/ThreatEntryAdditions.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/ThreatEntryRemovals.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/ThreatType.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/CompressionType.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ComputeThreatListDiffRequest.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ComputeThreatListDiffResponse.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/RawHashes.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/RawIndices.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/RiceDeltaEncoding.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchHashesRequest.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchHashesResponse.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchUrisRequest.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchUrisResponse.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ThreatEntryAdditions.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ThreatEntryRemovals.java
  proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ThreatType.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#168 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#170 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#172 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#177 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#183 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#185 feat: promote to GA
  .repo-metadata.json
  README.md
  synth.metadata
Labels: cla: yes

#187 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-webrisk/pom.xml
  grpc-google-cloud-webrisk-v1/pom.xml
  grpc-google-cloud-webrisk-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-webrisk-v1/pom.xml
  proto-google-cloud-webrisk-v1beta1/pom.xml
Labels: cla: yes

#192 fix: migrate retry settings to grpc_service_config
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/stub/WebRiskServiceStubSettings.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/WebRiskServiceV1Beta1StubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#203 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
