Repository googleapis/java-webrisk, pull requests merged in 2020-12, with the labels that each got.

#294 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#298 chore: migrate to microgenerator
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/WebRiskServiceClient.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/WebRiskServiceSettings.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/package-info.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/stub/GrpcWebRiskServiceCallableFactory.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/stub/GrpcWebRiskServiceStub.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/stub/WebRiskServiceStub.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/stub/WebRiskServiceStubSettings.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/WebRiskServiceV1Beta1Client.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/WebRiskServiceV1Beta1Settings.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/package-info.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/GrpcWebRiskServiceV1Beta1CallableFactory.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/GrpcWebRiskServiceV1Beta1Stub.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/WebRiskServiceV1Beta1Stub.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/WebRiskServiceV1Beta1StubSettings.java
  google-cloud-webrisk/src/test/java/com/google/cloud/webrisk/v1/MockWebRiskService.java
  google-cloud-webrisk/src/test/java/com/google/cloud/webrisk/v1/MockWebRiskServiceImpl.java
  google-cloud-webrisk/src/test/java/com/google/cloud/webrisk/v1/WebRiskServiceClientTest.java
  google-cloud-webrisk/src/test/java/com/google/cloud/webrisk/v1beta1/MockWebRiskServiceV1Beta1.java
  google-cloud-webrisk/src/test/java/com/google/cloud/webrisk/v1beta1/MockWebRiskServiceV1Beta1Impl.java
  google-cloud-webrisk/src/test/java/com/google/cloud/webrisk/v1beta1/WebRiskServiceV1Beta1ClientTest.java
  proto-google-cloud-webrisk-v1/src/main/java/com/google/webrisk/v1/ProjectName.java
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#300 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#306 samples: create Java sample for Search API and Submit API in Webrisk
  samples/snippets/src/main/java/webrisk/SearchUriExample.java
  samples/snippets/src/main/java/webrisk/SubmitUriExample.java
  samples/snippets/src/test/java/webrisk/SearchUriExampleTest.java
  samples/snippets/src/test/java/webrisk/SubmitUriExampleTest.java
Labels: api: webrisk, automerge, cla: yes, samples

#309 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#310 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#311 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#313 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: webrisk, cla: yes, context: full
