Repository googleapis/java-webrisk, pull requests merged in 2020-11, with the labels that each got.

#274 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#275 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#276 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#277 deps: update dependency com.google.cloud:google-cloud-shared-dependencies to v0.15.0
  pom.xml
Labels: api: webrisk, automerge, cla: yes

#281 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#279 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#285 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#286 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full, samples
