Repository googleapis/java-webrisk, pull requests merged in 2021-05, with the labels that each got.

#426 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: webrisk, automerge, cla: yes

#429 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#431 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#432 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#437 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#438 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#444 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#440 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#446 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: webrisk, cla: yes, context: full

#449 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes
