Repository googleapis/java-webrisk, pull requests merged in 2021-09, with the labels that each got.

#525 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/workflows/ci.yaml
  README.md
  google-cloud-webrisk-bom/pom.xml
  google-cloud-webrisk/pom.xml
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/stub/WebRiskServiceStubSettings.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/WebRiskServiceV1Beta1StubSettings.java
  owlbot.py
  pom.xml
  proto-google-cloud-webrisk-v1/clirr-ignored-differences.xml
  proto-google-cloud-webrisk-v1beta1/clirr-ignored-differences.xml
  renovate.json
  samples/snippets/src/main/java/webrisk/SearchUriExample.java
  samples/snippets/src/main/java/webrisk/SubmitUriExample.java
  samples/snippets/src/test/java/webrisk/SearchUriExampleTest.java
  samples/snippets/src/test/java/webrisk/SubmitUriExampleTest.java
  versions.txt
Labels: cla: yes, api: webrisk, automerge

#534 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: kokoro:force-run, cla: yes, api: webrisk, automerge

#546 chore: make owlbot check required
  .github/sync-repo-settings.yaml
  README.md
Labels: cla: yes, api: webrisk

#540 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: webrisk, automerge

#551 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: webrisk, automerge
