Repository googleapis/java-webrisk, pull requests merged in 2021-01, with the labels that each got.

#314 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, cla: yes

#315 chore: update gapic-generator-java to 0.0.16
  google-cloud-webrisk/src/test/java/com/google/cloud/webrisk/v1/WebRiskServiceClientTest.java
  google-cloud-webrisk/src/test/java/com/google/cloud/webrisk/v1beta1/WebRiskServiceV1Beta1ClientTest.java
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#316 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#318 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#319 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#320 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#321 chore: update gapic-generator-java to 0.0.18
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/WebRiskServiceClient.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/stub/GrpcWebRiskServiceCallableFactory.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/stub/WebRiskServiceStub.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1/stub/WebRiskServiceStubSettings.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/WebRiskServiceV1Beta1Client.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/WebRiskServiceV1Beta1Settings.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/GrpcWebRiskServiceV1Beta1CallableFactory.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/GrpcWebRiskServiceV1Beta1Stub.java
  google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/WebRiskServiceV1Beta1Stub.java
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#327 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: webrisk, automerge, cla: yes

#330 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: webrisk, automerge, cla: yes, context: full

#331 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: webrisk, automerge, cla: yes
